# Generated by Django 4.2.6 on 2023-10-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('studyspots', '0001_initial'), ('studyspots', '0002_delete_customuser'), ('studyspots', '0003_initial'), ('studyspots', '0004_delete_customuser'), ('studyspots', '0005_initial'), ('studyspots', '0006_studyspace_crowdedness_ratings'), ('studyspots', '0007_remove_studyspace_crookedness_ratings'), ('studyspots', '0008_remove_location_coordinates_location_lat_and_more'), ('studyspots', '0009_alter_location_link'), ('studyspots', '0010_rename_studyspace_studyspot')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('on_grounds', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('Library', 'Library'), ('Academic Building', 'Academic Building'), ('Outdoor', 'Outdoor'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudySpot',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Group Study Room', 'Group Study Room'), ('Conference Room', 'Conference Room'), ('Table', 'Table'), ('Public Area', 'Public Area'), ('Other', 'Other')], default='Other', max_length=20)),
                ('comments', models.JSONField(default=list)),
                ('reservable', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField()),
                ('overall_ratings', models.JSONField(default=list)),
                ('comfort_ratings', models.JSONField(default=list)),
                ('noise_level_ratings', models.JSONField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyspots.location')),
                ('crowdedness_ratings', models.JSONField(default=list)),
            ],
        ),
    ]
