# Generated by Django 4.2.6 on 2023-10-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('on_grounds', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('Library', 'Library'), ('Academic Building', 'Academic Building'), ('Outdoor', 'Outdoor'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('lat', models.FloatField(null=False)),
                ('lng', models.FloatField(null=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Group Study Room', 'Group Study Room'), ('Conference Room', 'Conference Room'), ('Table', 'Table'), ('Public Area', 'Public Area'), ('Other', 'Other')], default='Other', max_length=20)),
                ('comments', models.JSONField(default=list)),
                ('reservable', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField()),
                ('overall_ratings', models.JSONField(default=list)),
                ('comfort_ratings', models.JSONField(default=list)),
                ('crowdedness_ratings', models.JSONField(default=list)),
                ('noise_level_ratings', models.JSONField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyspots.location')),
            ],
        ),
    ]
