# Generated by Django 4.2.6 on 2023-10-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
