# Generated by Django 4.2.6 on 2023-10-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='crowdedness_ratings',
            field=models.JSONField(default=list),
        ),
    ]
