# Generated by Django 4.2.6 on 2023-10-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0006_studyspace_crowdedness_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspace',
            name='crookedness_ratings',
        ),
    ]
