# Generated by Django 4.2.6 on 2023-10-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0008_remove_location_coordinates_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
