# Generated by Django 4.2.6 on 2023-10-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0009_alter_location_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudySpace',
            new_name='StudySpot',
        ),
    ]
