# Generated by Django 4.2.6 on 2023-10-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0001_squashed_0010_rename_studyspace_studyspot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudySpot',
            new_name='StudySpace',
        ),
    ]
