# Generated by Django 4.2.5 on 2023-10-30 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0011_pendinglocation_pendingstudyspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingstudyspot',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyspots.pendinglocation'),
        ),
    ]
