# Generated by Django 4.2.5 on 2023-10-31 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('studyspots', '0012_alter_pendingstudyspot_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingstudyspot',
            name='location_id',
        ),
        migrations.AddField(
            model_name='pendingstudyspot',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pendingstudyspot',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
