# Generated by Django 4.2.6 on 2023-11-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0013_rename_space_id_studyspace_studyspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='studyspace_count',
            field=models.IntegerField(default=0),
        ),
    ]
