# Generated by Django 4.2.6 on 2023-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0014_location_studyspace_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='studyspace_count',
            new_name='studyspaces',
        ),
        migrations.AddField(
            model_name='studyspace',
            name='studyspace_in_location',
            field=models.IntegerField(default=0),
        ),
    ]
