# Generated by Django 4.2.6 on 2023-11-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0015_rename_studyspace_count_location_studyspaces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyspace',
            old_name='studyspace_in_location',
            new_name='in_location_ordinal',
        ),
        migrations.RemoveField(
            model_name='location',
            name='studyspaces',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('LIBRARY', 'Library'), ('ACADEMIC_BUILDING', 'Academic Building'), ('OUTDOOR', 'Outdoor'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='Other', max_length=20),
        ),
    ]
