# Generated by Django 4.2.6 on 2023-11-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0016_rename_studyspace_in_location_studyspace_in_location_ordinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='location_ordinal',
            field=models.IntegerField(default=-1),
        ),
    ]
