# Generated by Django 4.2.6 on 2023-11-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0017_remove_studyspace_in_location_ordinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspace',
            name='in_location_ordinal',
        ),
    ]
