# Generated by Django 4.2.6 on 2023-11-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('studyspots', '0018_remove_studyspace_in_location_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('Library', 'Library'), ('Academic Building', 'Academic Building'), ('Outdoor', 'Outdoor'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0.0, max_digits=10)),
                ('on_grounds', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingStudySpot',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Group Study Room', 'Group Study Room'), ('Conference Room', 'Conference Room'), ('Table', 'Table'), ('Public Area', 'Public Area'), ('Other', 'Other')], default='Other', max_length=20)),
                ('comments', models.JSONField(default=list)),
                ('reservable', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField()),
                ('overall_ratings', models.JSONField(default=list)),
                ('comfort_ratings', models.JSONField(default=list)),
                ('noise_level_ratings', models.JSONField(default=list)),
                ('crowdedness_ratings', models.JSONField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
