# Generated by Django 4.2.6 on 2023-11-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0018_remove_studyspace_in_location_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspace',
            name='comfort_ratings',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='studyspace',
            name='comments',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='studyspace',
            name='crowdedness_ratings',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='studyspace',
            name='noise_level_ratings',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='studyspace',
            name='overall_ratings',
            field=models.JSONField(default='{}'),
        ),
    ]
