# Generated by Django 4.2.6 on 2023-11-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0020_alter_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingstudyspot',
            old_name='space_id',
            new_name='studyspace_id',
        ),
    ]
