# Generated by Django 4.2.6 on 2023-11-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0023_admin_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='link',
        ),
        migrations.RemoveField(
            model_name='pendinglocation',
            name='link',
        ),
        migrations.RenameModel(
            old_name="pendingstudyspot",
            new_name="pendingstudyspace"
        )
    ]
