# Generated by Django 4.2.6 on 2023-11-05 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0024_remove_location_link_remove_pendinglocation_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingstudyspace',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studyspace',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
