# Generated by Django 4.2.6 on 2023-11-05 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyspots', '0025_alter_pendingstudyspace_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspace',
            name='capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
